# Generated by Django 4.1 on 2023-12-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_estimate_estimate_reference_estimate_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='adjustment',
            field=models.FloatField(default='0.00', null=True),
        ),
    ]
