# Generated by Django 4.1 on 2023-12-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_estimate_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate_item',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='estimate_item',
            name='estimate',
        ),
        migrations.DeleteModel(
            name='estimate',
        ),
        migrations.DeleteModel(
            name='estimate_item',
        ),
    ]
