# Generated by Django 4.1 on 2023-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_estimate_gst_number_estimate_gst_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='paid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
