# Generated by Django 4.1 on 2023-10-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20231025_0933'),
        ('app1', '0021_estimate_balance_estimate_paid'),
    ]

    operations = [
    ]
