# Generated by Django 4.1 on 2023-10-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_merge_20231025_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='gst_treatment',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], default='Draft', max_length=150),
        ),
    ]
