# Generated by Django 4.1 on 2023-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='del_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
