# Generated by Django 4.1 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_estimate_del_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='balance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='conversion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='credit_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='gst_treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='payment_term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
