# Generated by Django 4.1 on 2023-10-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_estimate_balance_alter_estimate_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='credit_term',
            new_name='payment_method',
        ),
    ]
