# Generated by Django 4.1 on 2023-10-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_rename_credit_term_estimate_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='del_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
