# Generated by Django 4.1 on 2023-10-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_estimate_del_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='del_status',
        ),
    ]
