# Generated by Django 4.1 on 2023-10-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_estimate_del_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='adjustment',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
